#!/usr/bin/env python3
"""Build the Cloudflare Pages bundle.

    python3 build_static.py            # writes public/ + functions/_core/data.js

Outputs
-------
public/                       static site uploaded to Cloudflare Pages
  index.html                  website + AI Navigator widget
  deck.html                   printable legal-partnership deck (HTML)
  deck.pdf / deck.md          pre-generated deck for the default legal group
  static/{info,journey,hotels,pilot,stats,intake-form}.json
                              static fallbacks so the page renders even if the
                              Functions backend is unavailable
functions/_core/data.js       the seed data inlined for the JS core
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from bot import deck as deck_mod            # noqa: E402
from bot import legal_desk, sponsors        # noqa: E402
from bot.channels import describe_adapters  # noqa: E402
from bot.config import load_config          # noqa: E402

PUBLIC = ROOT / "public"
CORE = ROOT / "functions" / "_core"


def main() -> int:
    if PUBLIC.exists():
        shutil.rmtree(PUBLIC)
    (PUBLIC / "static").mkdir(parents=True, exist_ok=True)
    CORE.mkdir(parents=True, exist_ok=True)

    data = sponsors.SponsorData(ROOT / "data" / "hotels.json")
    seed = data.as_dict()

    # ---- JS seed module -------------------------------------------------
    (CORE / "data.js").write_text(
        "// AUTO-GENERATED by build_static.py from data/hotels.json — do not edit by hand.\n"
        "export default " + json.dumps(seed, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )

    # ---- static site ----------------------------------------------------
    shutil.copy(ROOT / "web" / "index.html", PUBLIC / "index.html")

    opts = deck_mod.DeckOptions()
    (PUBLIC / "deck.html").write_text(deck_mod.deck_html(opts), encoding="utf-8")
    (PUBLIC / "deck.pdf").write_bytes(deck_mod.deck_pdf(opts))
    (PUBLIC / "deck.md").write_text(deck_mod.deck_markdown(opts), encoding="utf-8")

    cfg = load_config()
    info = {
        "platform": "Türkiye Startup Landing Platform",
        "program": "Iran → Türkiye Startup Bridge",
        "deployment": "Cloudflare Pages (static + Functions)",
        "channels": describe_adapters(cfg),
        "modules": [
            "Legal Landing Desk (Iran–Türkiye Startup Legal Desk)",
            "Startup Legal Intake Form",
            "Pre-Landing Legal Assessment",
            "Two-Layer Legal Model",
            "Sponsor model (hospitality / corporate / ecosystem)",
            "Istanbul Startup Hotel Map",
            "Corporate Startup Sponsorship + PoC flow",
            "AI Startup Navigator with Legal AI Safety Principle",
            "Pitch-deck generator for legal partners (MD/HTML/PDF)",
        ],
        "commands": ["/legal", "/intake", "/assessment", "/journey", "/hotels", "/corporate", "/deck", "/pilot", "/metrics", "/human", "/lang en|fa|tr"],
    }
    (PUBLIC / "static" / "info.json").write_text(json.dumps(info, ensure_ascii=False, indent=2), encoding="utf-8")
    (PUBLIC / "static" / "journey.json").write_text(
        json.dumps({"journey": legal_desk.JOURNEY, "layers": legal_desk.LAYERS}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (PUBLIC / "static" / "hotels.json").write_text(
        json.dumps(
            {
                "cities": sponsors.CITIES,
                "sponsor_types": sponsors.SPONSOR_TYPES,
                "hotels": [h.as_dict() for h in data.hotels],
                "corporate_sponsors": data.corporate,
                "ecosystem_sponsors": data.ecosystem,
                "legal_partners": data.legal_partners,
                "total_sponsored_rooms": sponsors.total_sponsored_rooms(data),
                "matches": sponsors.match_hotels(data, city="Istanbul", rooms_needed=3, needs_workspace=True),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    (PUBLIC / "static" / "pilot.json").write_text(
        json.dumps(
            {
                "pilot": legal_desk.PILOT,
                "applied": 100,
                "funnel": legal_desk.funnel_projection(100),
                "metrics": [dict(zip(("metric", "target"), m)) for m in legal_desk.SUCCESS_METRICS],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    (PUBLIC / "static" / "intake-form.json").write_text(
        json.dumps({"fields": legal_desk.INTAKE_FORM, "required": legal_desk.REQUIRED_INTAKE_KEYS}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (PUBLIC / "static" / "stats.json").write_text(
        json.dumps(
            {
                "mode": "stateless-edge",
                "startups": 0,
                "legal_cases": 0,
                "sponsored_rooms": sponsors.total_sponsored_rooms(data),
                "hotels": len(data.hotels),
                "corporate_sponsors": len(data.corporate),
                "note": "Pipeline counters live in the self-hosted Python service (GET /api/stats).",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    (PUBLIC / "_headers").write_text(
        "/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n"
        "  Permissions-Policy: geolocation=(), camera=(), microphone=()\n",
        encoding="utf-8",
    )

    files = sorted(str(p.relative_to(PUBLIC)) for p in PUBLIC.rglob("*") if p.is_file())
    print(f"built {len(files)} files into {PUBLIC.relative_to(ROOT)}/")
    for f in files:
        size = (PUBLIC / f).stat().st_size
        print(f"  {f:<28}{size:>9,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
