import { db } from "@/db";
import { hotels, corporates, startups, investors } from "@/db/schema";
import { sql } from "drizzle-orm";

export async function ensureSeeded() {
  const [row] = await db.execute<{ count: string }>(sql`select count(*)::text as count from hotels`).then((r) => r.rows);
  if (row && Number(row.count) > 0) return;

  const insertedHotels = await db
    .insert(hotels)
    .values([
      { name: "Bosphorus Bridge Hotel", city: "Istanbul", district: "Beşiktaş", lat: 41.0428, lng: 29.0075, sponsorLevel: "gold", supportType: "free", startupRooms: 10, roomsAvailable: 7, meetingRoom: true, coworking: true, airportTransfer: true, metroMinutes: 4, exhibitionMinutes: 25, sectors: ["AI", "Fintech", "SaaS"], description: "Flagship partner. Dedicated startup floor with coworking and a 40-seat pitch room." },
      { name: "Levent Business Suites", city: "Istanbul", district: "Levent", lat: 41.0815, lng: 29.0119, sponsorLevel: "silver", supportType: "discount50", startupRooms: 5, roomsAvailable: 3, meetingRoom: true, coworking: false, airportTransfer: false, metroMinutes: 2, exhibitionMinutes: 20, sectors: ["Fintech", "Enterprise"], description: "In the heart of the financial district, steps from corporate HQs." },
      { name: "Kadıköy Maker Inn", city: "Istanbul", district: "Kadıköy", lat: 40.9903, lng: 29.0275, sponsorLevel: "bronze", supportType: "discount50", startupRooms: 4, roomsAvailable: 4, meetingRoom: false, coworking: true, airportTransfer: false, metroMinutes: 6, exhibitionMinutes: 40, sectors: ["Hardware", "IoT", "Creative"], description: "Asian-side creative hub with a maker space in the basement." },
      { name: "Yeşilköy Expo Hotel", city: "Istanbul", district: "Bakırköy", lat: 40.9765, lng: 28.8213, sponsorLevel: "gold", supportType: "corporate", startupRooms: 12, roomsAvailable: 9, meetingRoom: true, coworking: true, airportTransfer: true, metroMinutes: 5, exhibitionMinutes: 5, sectors: ["All"], description: "Five minutes from Istanbul Expo Center — the GITEX AI Türkiye landing base." },
      { name: "Maslak Tech Residence", city: "Istanbul", district: "Maslak", lat: 41.1094, lng: 29.0212, sponsorLevel: "silver", supportType: "free", startupRooms: 6, roomsAvailable: 2, meetingRoom: true, coworking: true, airportTransfer: false, metroMinutes: 3, exhibitionMinutes: 30, sectors: ["AI", "Deep Tech", "Energy"], description: "Next to İTÜ Arı Teknokent — ideal for deep-tech teams." },
      { name: "Çankaya Diplomat Hotel", city: "Ankara", district: "Çankaya", lat: 39.9035, lng: 32.8597, sponsorLevel: "gold", supportType: "free", startupRooms: 6, roomsAvailable: 6, meetingRoom: true, coworking: false, airportTransfer: true, metroMinutes: 8, exhibitionMinutes: 25, sectors: ["GovTech", "Defense", "Energy"], description: "Close to ministries and ODTÜ Teknokent." },
      { name: "Bilkent Innovation Lodge", city: "Ankara", district: "Bilkent", lat: 39.8681, lng: 32.7488, sponsorLevel: "bronze", supportType: "corporate", startupRooms: 3, roomsAvailable: 1, meetingRoom: true, coworking: true, airportTransfer: false, metroMinutes: 15, exhibitionMinutes: 35, sectors: ["HealthTech", "EdTech"], description: "Corporate-sponsored rooms inside the Bilkent Cyberpark ecosystem." },
      { name: "Alsancak Harbour Hotel", city: "İzmir", district: "Alsancak", lat: 38.4370, lng: 27.1428, sponsorLevel: "silver", supportType: "discount50", startupRooms: 4, roomsAvailable: 4, meetingRoom: false, coworking: true, airportTransfer: true, metroMinutes: 5, exhibitionMinutes: 20, sectors: ["AgriTech", "Logistics", "Tourism"], description: "Aegean gateway for AgriTech and logistics startups." },
    ])
    .returning({ id: hotels.id });

  const insertedCorporates = await db
    .insert(corporates)
    .values([
      { name: "Anadolu Enerji Holding", industry: "Energy", city: "Istanbul", lookingFor: ["Energy AI", "Grid Optimization", "Battery Analytics"], sponsorTier: "strategic", teamsSponsored: 3, budgetUsd: 150000, offersPoc: true, offersOffice: true, offersInvestment: true, description: "Seeking AI teams for renewable forecasting and grid load optimization." },
      { name: "Marmara Lojistik", industry: "Logistics", city: "Istanbul", lookingFor: ["Route Optimization", "Fleet AI", "Warehouse Robotics"], sponsorTier: "innovation", teamsSponsored: 1, budgetUsd: 50000, offersPoc: true, offersOffice: false, offersInvestment: false, description: "Regional logistics operator running 1,200 trucks between Türkiye, Iran and Europe." },
      { name: "Ege Tarım Grubu", industry: "Agriculture", city: "İzmir", lookingFor: ["AgriTech", "Precision Irrigation", "Crop Analytics"], sponsorTier: "innovation", teamsSponsored: 1, budgetUsd: 40000, offersPoc: true, offersOffice: true, offersInvestment: false, description: "Largest olive & citrus exporter in the Aegean region." },
      { name: "Boğaziçi İnşaat", industry: "Construction", city: "Istanbul", lookingFor: ["ConstructionTech", "BIM AI", "Site Safety"], sponsorTier: "strategic", teamsSponsored: 2, budgetUsd: 120000, offersPoc: true, offersOffice: true, offersInvestment: true, description: "Building 14 large-scale projects; wants digital twins and safety AI." },
      { name: "Kapadokya Turizm", industry: "Tourism", city: "Ankara", lookingFor: ["TravelTech", "Booking AI", "Guest Experience"], sponsorTier: "innovation", teamsSponsored: 1, budgetUsd: 35000, offersPoc: true, offersOffice: false, offersInvestment: false, description: "Hotel & tour group with 9 properties looking for guest-experience AI." },
      { name: "Ankara Makina Sanayi", industry: "Manufacturing", city: "Ankara", lookingFor: ["Industrial Automation", "Predictive Maintenance", "Computer Vision QC"], sponsorTier: "strategic", teamsSponsored: 2, budgetUsd: 90000, offersPoc: true, offersOffice: true, offersInvestment: true, description: "CNC and industrial machinery manufacturer with 3 plants." },
      { name: "İstanbul Sağlık Grubu", industry: "Healthcare", city: "Istanbul", lookingFor: ["HealthTech", "Medical Imaging AI", "Patient Flow"], sponsorTier: "innovation", teamsSponsored: 0, budgetUsd: 60000, offersPoc: true, offersOffice: false, offersInvestment: true, description: "Private hospital group with 6 hospitals; medical tourism focus." },
    ])
    .returning({ id: corporates.id });

  const h = insertedHotels.map((x) => x.id);
  const c = insertedCorporates.map((x) => x.id);

  await db.insert(startups).values([
    { name: "GridMind AI", tagline: "Renewable generation forecasting for utilities", sector: "Energy AI", stage: "revenue", founderName: "Sara Mohammadi", technicalName: "Amir Rezaei", businessName: "Nima Karimi", tractionSummary: "3 paying utilities in Iran, 94% forecast accuracy", seekingUsd: 400000, needsCorporate: ["Energy", "Utilities"], status: "poc", sourceEvent: "Elcom 2025", hotelId: h[4], corporateId: c[0], landingStep: 7 },
    { name: "RouteX", tagline: "Cross-border fleet routing and customs prediction", sector: "Logistics AI", stage: "mvp", founderName: "Reza Ahmadi", technicalName: "Leila Hosseini", businessName: "Kian Farahani", tractionSummary: "Pilot with 2 freight forwarders, 18% fuel savings", seekingUsd: 250000, needsCorporate: ["Logistics", "Freight"], status: "landed", sourceEvent: "GITEX AI Türkiye 2026", hotelId: h[0], corporateId: c[1], landingStep: 5 },
    { name: "SiteGuard Vision", tagline: "Computer-vision safety monitoring for construction sites", sector: "ConstructionTech", stage: "revenue", founderName: "Mina Sadeghi", technicalName: "Hamed Nouri", businessName: "Arash Jafari", tractionSummary: "Deployed on 11 sites, 40% fewer incidents", seekingUsd: 500000, needsCorporate: ["Construction", "Infrastructure"], status: "funded", sourceEvent: "Elcom 2025", hotelId: h[0], corporateId: c[3], landingStep: 9 },
    { name: "AgroPulse", tagline: "Precision irrigation with satellite + soil sensors", sector: "AgriTech", stage: "mvp", founderName: "Parisa Ghasemi", technicalName: "Babak Moradi", businessName: "Shirin Tavakoli", tractionSummary: "400 hectares under management", seekingUsd: 200000, needsCorporate: ["Agriculture", "Food Export"], status: "selected", sourceEvent: "University Demo Day", hotelId: h[7], corporateId: c[2], landingStep: 3 },
    { name: "MediFlow", tagline: "Patient flow optimization for hospital operations", sector: "HealthTech", stage: "mvp", founderName: "Dr. Hossein Zare", technicalName: "Yasaman Rahimi", businessName: "Pouya Ebrahimi", tractionSummary: "2 hospital pilots, 22% shorter ER wait", seekingUsd: 300000, needsCorporate: ["Healthcare", "Hospitals"], status: "selected", sourceEvent: "Elcom 2025", hotelId: h[1], corporateId: c[6], landingStep: 2 },
    { name: "TorqueSense", tagline: "Predictive maintenance for CNC and industrial machinery", sector: "Industrial IoT", stage: "revenue", founderName: "Mehdi Kazemi", technicalName: "Fatemeh Alavi", businessName: "Saeed Rostami", tractionSummary: "14 factories, 31% unplanned downtime reduction", seekingUsd: 350000, needsCorporate: ["Manufacturing", "Automotive"], status: "landed", sourceEvent: "Elcom 2025", hotelId: h[5], corporateId: c[5], landingStep: 6 },
    { name: "StayGenie", tagline: "AI guest concierge for boutique hotels", sector: "TravelTech", stage: "idea", founderName: "Niloufar Amini", technicalName: "Ali Shariati", businessName: "Roxana Bahrami", tractionSummary: "Waitlist of 60 hotels", seekingUsd: 120000, needsCorporate: ["Tourism", "Hospitality"], status: "pool", sourceEvent: "GITEX AI Türkiye 2026", landingStep: 0 },
    { name: "PayBridge", tagline: "Cross-border SME payments and FX hedging", sector: "Fintech", stage: "mvp", founderName: "Kamran Yousefi", technicalName: "Elham Naseri", businessName: "Dariush Salehi", tractionSummary: "$2M monthly volume in sandbox", seekingUsd: 600000, needsCorporate: ["Banking", "Trade"], status: "pool", sourceEvent: "Elcom 2025", landingStep: 0 },
    { name: "LearnLoop", tagline: "Adaptive Turkish-language upskilling for engineers", sector: "EdTech", stage: "mvp", founderName: "Maryam Hashemi", technicalName: "Omid Sharifi", businessName: "Bahar Mousavi", tractionSummary: "9,000 learners, 4.7 rating", seekingUsd: 150000, needsCorporate: ["Education", "HR"], status: "pool", sourceEvent: "University Demo Day", landingStep: 0 },
    { name: "SolarSpec", tagline: "Drone-based defect detection for solar farms", sector: "Energy AI", stage: "idea", founderName: "Farhad Jalali", technicalName: "Negin Rahmani", businessName: "Soroush Danesh", tractionSummary: "Prototype tested on 2 farms", seekingUsd: 100000, needsCorporate: ["Energy", "Solar"], status: "pool", sourceEvent: "Elcom 2025", landingStep: 0 },
  ]);

  await db.insert(investors).values([
    { name: "Bosphorus Ventures", type: "vc", city: "Istanbul", ticketMinUsd: 250000, ticketMaxUsd: 2000000, sectors: ["AI", "Fintech", "SaaS"], stages: ["mvp", "revenue"], thesis: "Seed and Series A in B2B software with regional expansion potential." },
    { name: "Anatolia Angels Network", type: "angel", city: "Ankara", ticketMinUsd: 25000, ticketMaxUsd: 200000, sectors: ["Deep Tech", "HealthTech", "Industrial IoT"], stages: ["idea", "mvp"], thesis: "60 angel investors backing technical founders early." },
    { name: "Marmara Corporate Ventures", type: "corporate", city: "Istanbul", ticketMinUsd: 100000, ticketMaxUsd: 1000000, sectors: ["Logistics AI", "Energy AI", "ConstructionTech"], stages: ["revenue", "scaling"], thesis: "Strategic investments following a successful PoC with a portfolio corporate." },
    { name: "İTÜ Çekirdek", type: "accelerator", city: "Istanbul", ticketMinUsd: 10000, ticketMaxUsd: 50000, sectors: ["All"], stages: ["idea", "mvp"], thesis: "Türkiye's largest university-based accelerator; office at Arı Teknokent." },
    { name: "Aegean Growth Fund", type: "vc", city: "İzmir", ticketMinUsd: 200000, ticketMaxUsd: 1500000, sectors: ["AgriTech", "TravelTech", "Logistics AI"], stages: ["mvp", "revenue"], thesis: "Backing food, tourism and trade technology out of the Aegean." },
    { name: "Teknopark İstanbul Fund", type: "corporate", city: "Istanbul", ticketMinUsd: 50000, ticketMaxUsd: 500000, sectors: ["Deep Tech", "Defense", "Energy AI"], stages: ["mvp", "revenue"], thesis: "Investing in technopark-resident companies with export potential." },
  ]);
}
